# Generated by Django 4.0.3 on 2022-04-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Difficulty', models.FloatField(default=0.0)),
                ('Query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('IsTeacher', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('AcceptRate', models.FloatField(default=0.0)),
                ('ProblemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.problem')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('ProblemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.problem')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
        migrations.CreateModel(
            name='RegClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.class')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('StartDateTime', models.DateTimeField()),
                ('EndDateTime', models.DateTimeField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.class')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='Query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.query'),
        ),
        migrations.AddField(
            model_name='class',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users'),
        ),
    ]
