# Generated by Django 4.0.3 on 2022-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addclass_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='classname',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
