# Generated by Django 4.0.3 on 2022-04-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_rename_profname_addclass_profid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addClass',
            new_name='Class',
        ),
        migrations.AddField(
            model_name='quiz',
            name='Classid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
