# Generated by Django 4.0.3 on 2022-04-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_regclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='regclass',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.FloatField(default=0)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
