# Generated by Django 4.0.3 on 2022-04-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quiz_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='data',
            new_name='date',
        ),
    ]
