# Generated by Django 4.0.3 on 2022-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_quiz_endtime_quiz_problemnum_quiz_sqlkeyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
